version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Hello printhello
          command: |
            echo 'Hello World'
            echo 'This is from Herves'
