version: 2.1

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Hello printhello
          command: |
            echo 'Hello World'
            echo 'This is from Herves'
  build2:
    docker:
      - image: alpine
    steps:
      - run:
          name: Second printhello
          command: |
            echo 'Salut le monde'
            echo 'Ca va?'
  node-version:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - run:
          name: running node in container
          command: |
            node -v
  top-secret-build:
    docker:
      - image: alpine
    steps:
      - run:
          name: jamesbond
          command: |
            echo 'Top secret needs approval'
workflows:
  version: 2
  Example-workflow:
    jobs:
      - build
      - build2:
          requires:
            - build
      - node-version
      - Hold-For-Approval:
          type: approval
      - top-secret-build:
          requires:
            - Hold-For-Approval
